filial = Filial.find_or_create_by(name: 'Escritorio', address: 'Santarém', category: 1)
filial2 = Filial.find_or_create_by(name: 'Projeto Rodrigo', address: 'Prainha', category: 2)

User.find_or_create_by(name: 'Admin', email: 'admin@gmail.com', filial: filial, role: 1) do |u|
  u.password = '12345678'
  u.save
end
User.find_or_create_by(name: 'Pedrinho', email: 'pedrinho@gmail.com', filial: filial2, role: 2) do |u|
  u.password = '12345678'
  u.save
end

Product.all.destroy_all
# PRODUCTS
array = [
  {name: "PINO TEMPERADO", reference: "774560", quantity: 2},
  {name: "ROTULA PISTÃO D6M RTB", reference: "2057986", quantity: 3},
  {name: "ROTULA PISTÃO ", reference: "GE7OES", quantity: 4},
  {name: "ROTULA SKIDDER MULLER", reference: "CTP-8G4189", quantity: 3},
  {name: "ROTULA", reference: "GEZ57ES", quantity: 1},
  {name: "ROTULA", reference: "GE60ES", quantity: 1},
  {name: "ROTULA", reference: "GEZ44ES", quantity: 1},
  {name: "ROTULA", reference: "GE45ES", quantity: 1},
  {name: "BUCHA", reference: "4V2883", quantity: 5},
  {name: "BUCHA", reference: "3602312", quantity: 2},
  {name: "BUCHA", reference: "4V2873", quantity: 3},
  {name: "BUCHA", reference: "E 158734/P", quantity: 1},
  {name: "JUNTA(IMPACTO)", reference: "2721956", quantity: 6},
  {name: "ORING( CAT)", reference: "5J3886", quantity: 1},
  {name: "ORING( CAT)", reference: "2013321", quantity: 2},
  {name: "ORING( CAT)", reference: "5J3886", quantity: 1},
  {name: "ORING( CAT)", reference: "8M4432", quantity: 4},
  {name: "ORING( CAT)", reference: "1172983", quantity: 1},
  {name: "ORING( CAT)", reference: "1473061", quantity: 4},
  {name: "ORING( CAT)", reference: "3J1907", quantity: 4},
  {name: "ORING( CAT)", reference: "1482903", quantity: 6},
  {name: "ORING( CAT)", reference: "2M9780", quantity: 2},
  {name: "ORING( CAT)", reference: "7M8485", quantity: 1},
  {name: "ORING( CAT)", reference: "1125282", quantity: 1},
  {name: "ORING( CAT)", reference: "104-6730", quantity: 1},
  {name: "ORING( CAT)", reference: "6J2419", quantity: 4},
  {name: "ORING( CAT)", reference: "3D2824", quantity: 4},
  {name: "ORING( CAT)", reference: "8S0768", quantity: 6},
  {name: "RETAINER", reference: "295-0993", quantity: 3},
  {name: "ORING", reference: "1504165", quantity: 6},
  {name: "ORING", reference: "3J1907", quantity: 6},
  {name: "REPARO BASCULHAMENTO(IMPACTO)", reference: "3367346", quantity: 4},
  {name: "REPARO LEVANTE(WORD GASKET)", reference: "2275347", quantity: 9},
  {name: "ORING(WORD GASKET)", reference: "2701528", quantity: 2},
  {name: "RETENTOR(IMPACTO)", reference: "1154109", quantity: 1},
  {name: "RETENTOR (ITR)", reference: "2223910", quantity: 1},
  {name: "PARAFUSOS (IMPACTO)", reference: "5V2973", quantity: 10},
  {name: "PARAFUSOS (IMPACTO)", reference: "4E 5985", quantity: 20},
  {name: "ABRAÇADEIRAS (IMPACTO)", reference: "4E 5984", quantity: 10},
  {name: "ABRAÇADEIRAS (IMPACTO)", reference: "4E 3273", quantity: 10},
  {name: "ROLAMENTO (CAT)", reference: "1B-3980", quantity: 2},
  {name: "PARAFUSOS (CAT)", reference: "8T0368", quantity: 5},
  {name: "ORING(CAT)", reference: "113-5304", quantity: 1},
  {name: "ORING(CAT)", reference: "4J-2506", quantity: 2},
  {name: "ORING (CAT)", reference: "149-5240", quantity: 6},
  {name: "ORING (CAT)", reference: "4F-4097", quantity: 2},
  {name: "ORING (CAT)", reference: "240-4695", quantity: 1},
  {name: "ORING (CAT)", reference: "133-3715", quantity: 6},
  {name: "ORING (CAT)", reference: "3J1907", quantity: 3},
  {name: "ORING (CAT)", reference: "295-0093", quantity: 1},
  {name: "ORING (CAT)", reference: "113-5304", quantity: 3},
  {name: "CHAVE DE INGUINIÇÃO( ITR)", reference: "9G7641", quantity: 3},
  {name: "BIELA(BEARING)", reference: "7W9415", quantity: 4},
  {name: "BRONZINA  DE BIELA (MAHLE)", reference: "5B13144", quantity: 4},
  {name: "RETENTORES DUO-CONE(REVESLAM)", reference: "9W6647", quantity: 2},
  {name: "COXIN TRANS CAT ( GHINASSI)", reference: "3116 G9W9920", quantity: 3},
  {name: "RETENTOR", reference: "CTP-1154120", quantity: 1},
  {name: "BOMBA DÁGUA", reference: "3522109", quantity: 1},
  {name: "BOMBA DÁGUA (938G SERIE 2)", reference: "3522138", quantity: 1},
  {name: "BOMBA DÁGUA", reference: "VBO 380", quantity: 1},
  {name: "MOTOR DE PARTIDA", reference: "393R12V", quantity: 1},
  {name: "VALVULA ", reference: "2333", quantity: 1},
  {name: "BOMBA DE TRANSFERENCIA", reference: "D/K6650", quantity: 1},
  {name: "REGULADOR DE PRESSÃO", reference: "54468", quantity: 1},
  {name: "BOMBA DE COMBUSTÍVEL", reference: "KO354", quantity: 1},
  {name: "VALVULA PROTEÇÃO", reference: "IT15588-60", quantity: 1},
  {name: "DLIVESHAFT /SEMI EIXO", reference: "27060", quantity: 1},
  {name: "SEMI EIXO HOMOCINETICA", reference: "953362", quantity: 1},
  {name: "REPARO COMPLETO DA PINÇA DE FREIO", reference: "MG- 4003", quantity: 1},
  {name: "BALANCIM COMPLETO MOTOR", reference: "2RK109443 B", quantity: 1},
  {name: "TAMPA DO TANQUE ", reference: "TC-1020", quantity: 1},
  {name: "RELE AUXILIAR ", reference: "29MT24V", quantity: 2},
  {name: "SACA POLIA 3 GARRAS", reference: "8565-2", quantity: 1},
  {name: "SELO DE PISTÃO EXTERNO TIPO LABÍO", reference: "7G-5674", quantity: 3},
  {name: "SELO DE PISTÃO EXTERNO TIPO LABÍO", reference: "7G-9224", quantity: 3},
  {name: "KIT SELO", reference: "8T-6397", quantity: 3},
  {name: "KIT SELO", reference: "8T-1378", quantity: 2},
  {name: "KIT SELO", reference: "241-7584", quantity: 1},
  {name: "KIT SELO", reference: "227-7547", quantity: 1},
  {name: "KIT SELO", reference: "243-5801", quantity: 1},
  {name: "KIT SELO", reference: "381-2331", quantity: 1},
  {name: "KIT SELO", reference: "376-9611", quantity: 1},
  {name: "SELO- RETENTOR DO GUINCHO", reference: "9F-5088", quantity: 1},
  {name: "GP DE SELO", reference: "9W-7209", quantity: 1},
  {name: "ANEL DO PISTÃO( CTP)", reference: "197-9386", quantity: 6},
  {name: "ANEL DO PISTÃO( BLUMA)", reference: "107-7630", quantity: 5},
  {name: "JUNTA (CAT)", reference: "300-7933", quantity: 5},
  {name: "COXIM DIANTEIRO MOTOR D6", reference: "6N-3256", quantity: 2},
  {name: "COXIM TRASEIRO MOTOR D6", reference: "6N-2549", quantity: 2},
  {name: "REPARO DA GARRAFA DE GIRO", reference: "CT-3105478", quantity: 2},
  {name: "VEDAÇÃO DO CARTUCHO DA BOMBA HIDRAULICA", reference: "1171911", quantity: 4},
  {name: "VEDAÇÃO DO CARTUCHO DA BOMBA HIDRAULICA", reference: "619457", quantity: 1},
  {name: "VEDAÇÃO DO CARTUCHO DA BOMBA HIDRAULICA", reference: "3F5792", quantity: 1},
  {name: "VEDAÇÃO DO CARTUCHO DA BOMBA HIDRAULICA", reference: "3G1820", quantity: 1},
  {name: "VEDAÇÃO DO CARTUCHO DA BOMBA HIDRAULICA", reference: "9T5087", quantity: 1},
  {name: "VEDAÇÃO DO CARTUCHO DA BOMBA HIDRAULICA", reference: "8C3079", quantity: 4},
  {name: "CUPULA PLÁSTICA D6M", reference: "CTP-6H 8021", quantity: 2},
  {name: "PRÉ-PURIFICADOR", reference: "CTT-1306 859", quantity: 1},
  {name: "KIT ACESSÓRIO DO CUBI DE RODA TRASEIRO", reference: "56005K", quantity: 0},
  {name: "GRACHEIRA YAMAGUCHI", reference: "35654", quantity: 1},
  {name: "MANCAL DO MOTOR", reference: "12975", quantity: 1},
  {name: "ROLAMENTO ", reference: "42381", quantity: 1},
  {name: "CAPA DO ROLAMENTO", reference: "JLM813010", quantity: 1},
  {name: "CAPA ", reference: "4T-42584", quantity: 1},
  {name: "CAPA", reference: "9D-3241/42", quantity: 1},
  {name: "CAPA ROLAMENTO", reference: "4T-42620", quantity: 1},
  {name: "ROLAMENTO", reference: "2K9295", quantity: 1},
  {name: "ROLAMENTO", reference: "LH2802", quantity: 1},
  {name: "CRUZETA", reference: "801019", quantity: 1},
  {name: "CRUZETA", reference: "HCZ 108", quantity: 1},
  {name: "CRUZETA", reference: "HCZ 128", quantity: 1},
  {name: "CRUZETA", reference: "HCZ 176", quantity: 2},
  {name: "CRUZETA", reference: "801020", quantity: 1},
  {name: "CRUZETA CARDAN", reference: "MEC-76002604", quantity: 2},
  {name: "CRUZETA", reference: "HCZ 113", quantity: 1},
  {name: "CRUZETA(CAT)", reference: "193-4640", quantity: 1},
  {name: "CRUZETA", reference: "801001", quantity: 1},
  {name: "CRUZETA", reference: "HCZ 252", quantity: 1},
  {name: "CRUZETA", reference: "HCZ 299", quantity: 1},
  {name: "CRUZETA", reference: "HCZ 254", quantity: 2},
  {name: "CRUZETA", reference: "HCZ 256", quantity: 1},
  {name: "CRUZETA", reference: "91702", quantity: 1},
  {name: "CRUZETA", reference: "VKUA-4584 A", quantity: 4},
  {name: "CRUZETA", reference: "801037", quantity: 1},
  {name: "CRUZETA", reference: "HCZ 143", quantity: 1},
  {name: "CRUZETA", reference: "VKVA 4590 A", quantity: 1},
  {name: "CRUZETA", reference: "VKVA 4590 A", quantity: 1},
  {name: "CRUZETA", reference: "HCZ 270", quantity: 1},
  {name: "BOMBA DE ÓLEO HIDRAULICO", reference: "938G", quantity: 2},
  {name: "PIVO INFEIROR LD/LE", reference: "PVI-9162", quantity: 2},
  {name: "PIVO SUSPENÇÃO", reference: "PVS-9162", quantity: 2},
  {name: "REPARO COMPELTO DA PINÇA DE FREIO", reference: "MG-4034", quantity: 2},
  {name: "BATENTE DA SUSPENÇÃO DO CAMBIO", reference: "R-7013", quantity: 2},
  {name: "JOGO DE MOLAS COMPLETO DO FREIO", reference: "MG-2197", quantity: 3},
  {name: "REGULADOR DE FREIO AUTOMATICO", reference: "MG-2194", quantity: 1},
  {name: "L 200-300", reference: "MG-2042", quantity: 1},
  {name: "REGULADOR DE FREIO AUTOMATICO", reference: "MG-2195", quantity: 1},
  {name: "REGULADOR DE FREIO AUTOMATICO", reference: "MG-2119", quantity: 1},
  {name: "JOGO DE MOLAS COMPLETO DO FREIO", reference: "MG-2118", quantity: 1},
  {name: "BARRA ESTABILIZADORA", reference: "JTSB0169009", quantity: 2},
  {name: "JOGO DE REPARO", reference: "4324101202", quantity: 3},
  {name: "JUNTA DE VEDAÇÃO", reference: "30501", quantity: 2},
  {name: "ROLAMENTO", reference: "6202.2ZR.A4", quantity: 19},
  {name: "ROLAMENTO", reference: "63022RSC3", quantity: 14},
  {name: "ROLAMENTO", reference: "62201 2RS/C3", quantity: 4},
  {name: "ROLAMENTO", reference: "6003-2RSH", quantity: 6},
  {name: "ROLAMENTO", reference: "63052-RSC3", quantity: 11},
  {name: "ROLAMENTO", reference: "6302", quantity: 5},
  {name: "ROLAMENTO", reference: "62201 2RS", quantity: 4},
  {name: "ROLAMENTO", reference: "6003 DDU", quantity: 7},
  {name: "ROLAMENTO", reference: "62062RSC3", quantity: 2},
  {name: "ROLAMENTO", reference: "6305-2RS1", quantity: 7},
  {name: "ROLAMENTO", reference: "6003-2RSH", quantity: 5},
  {name: "ROLAMENTO", reference: "6302 DDU", quantity: 7},
  {name: "ROLAMENTO", reference: "V62305", quantity: 1},
  {name: "ROLAMENTO", reference: "B17-99T1XDDG8LG16E", quantity: 1},
  {name: "ROLAMENTO", reference: "6303DDUC3", quantity: 1},
  {name: "ROLAMENTO", reference: "6302-2RS", quantity: 6},
  {name: "ROLAMENTO", reference: "6203-2RS", quantity: 1},
  {name: "ROLAMENTO", reference: "6202-2RS", quantity: 1},
  {name: "ROLAMENTO", reference: "6001-2RS", quantity: 1},
  {name: "ROLAMENTO", reference: "6304", quantity: 5},
  {name: "ROLAMENTO", reference: "528946", quantity: 1},
  {name: "ROLAMENTO", reference: "33022-9X026", quantity: 2},
  {name: "ROLAMENTO", reference: "N-32026XV", quantity: 1},
  {name: "ROLAMENTO", reference: "6306-2RS", quantity: 2},
  {name: "ROLAMENTO", reference: "6209-ZZ", quantity: 2},
  {name: "ROLAMENTO", reference: "JLM104910", quantity: 2},
  {name: "ROLAMENTO", reference: "7H9566/0054834", quantity: 6},
  {name: "ROLAMENTO", reference: "4T-JLM104948", quantity: 2},
  {name: "ROLAMENTO", reference: "6209.2ZR.A4", quantity: 3},
  {name: "ROLAMENTO", reference: "32306", quantity: 1},
  {name: "ROLAMENTO", reference: "6011DDUC3", quantity: 1},
  {name: "ROLAMENTO", reference: "33111", quantity: 1},
  {name: "ROLAMENTO", reference: "6I8849/60", quantity: 6},
  {name: "ROLAMENTO", reference: "BL309ZNR-C3", quantity: 1},
  {name: "ROLAMENTO", reference: "BL310ZNR-C3", quantity: 2},
  {name: "ROLAMENTO", reference: "4T-42687/42620", quantity: 1},
  {name: "ROLAMENTO", reference: "BZ-0030", quantity: 1},
  {name: "ROLAMENTO", reference: "42381", quantity: 1},
  {name: "ROLAMENTO", reference: "42584", quantity: 1},
  {name: "ROLAMENTO", reference: "4T-JM612910PK", quantity: 1},
  {name: "LUVA DO CARDAN", reference: "LV1345", quantity: 1},
  {name: "POLIA DO ALTERNADOR", reference: " 35 E 75 R-3818", quantity: 1},
  {name: "CUBO DE RODA", reference: "C11M374", quantity: 1},
  {name: "BOMBA DE DIREÇÃO VOLVO", reference: "46008", quantity: 1},
  {name: "TENSOR CORREA", reference: "20115", quantity: 4},
  {name: "ROLO TENSOR", reference: "5320195100", quantity: 1},
  {name: "POLIA DESVIADORA", reference: "13185", quantity: 1},
  {name: "POLIA DESVIADORA", reference: "13184", quantity: 1},
  {name: "TENSIONADOR", reference: "13243", quantity: 1},
  {name: "ESTICADOR DE CORREA ", reference: "MIC1687/14", quantity: 1},
  {name: "AJUSTADOR MANUAL", reference: "FM46", quantity: 2},
  {name: "COXIN DIANTEIRO E TRAS. DA SUSP DO MOTOR", reference: "R-375", quantity: 3},
  {name: "COXIN DO MOTOR L200 TRITON", reference: "7080", quantity: 1},
  {name: "ROTAMENTO DE CENTRO", reference: "R-3062", quantity: 1},
  {name: "TERMINAL DE DIREÇÃO", reference: "P1918B", quantity: 2},
  {name: "TERMINAL DE DIREÇÃO", reference: "ZL7380B", quantity: 1},
  {name: "TERMINAL DE DIREÇÃO", reference: "ZL7380B", quantity: 1},
  {name: " CONJUNTO DE SUPORTE DE COXINS DA CABINE", reference: "R-631", quantity: 2},
  {name: "BUCHA DO OLHAL DA MOLA DA SUSPENÇAO", reference: "R-3265", quantity: 3},
  {name: "CONJUNTOS DE BUCHAS DA BARRA ESTABIL", reference: "R-3250", quantity: 1},
  {name: "COXIN DO MANCAL COM ROLAMENTO 40 M.M", reference: "R-968R", quantity: 1},
  {name: "COXIN DIANTEIRO DA SUSPENÇÃO DO MOTOR", reference: "R-320", quantity: 2},
  {name: "REFIL COM ROLAMENTO DIANTEIRO 40 M.M", reference: "R-3056", quantity: 1},
  {name: "BUCHA DO BRAÇO E CAVALETE DA BARRA", reference: "R-3375", quantity: 2},
  {name: "BATENTE DA MOLA DA SUSPENÇÃO", reference: "R-2280", quantity: 2},
  {name: "BUCHA DO BRAÇO E CAVALETE DA BARRA", reference: "R-3374", quantity: 1},
  {name: "CINTA PROTEÇÃO DO TAMQUE COMBUSTIVEL", reference: "R-112", quantity: 2},
  {name: "BATENTE AUXILIAR DA MOLA SUSPENÇÃO", reference: "R-3241", quantity: 1},
  {name: "BUCHA DA BARRA ESTABIL DA SUSPENÇÃO", reference: "R-328", quantity: 2},
  {name: "BUCHA DA BARRA ESTABIL DA SUSPENÇÃO", reference: "R-3372", quantity: 1},
  {name: "MEIA BUCHA DA BARRA ESTABILIZADORA", reference: "R-459", quantity: 5},
  {name: "BUCHA DA BARRA ESTABIL DA SUSPENÇÃO", reference: "R-496", quantity: 2},
  {name: "KIT DE REPARO ", reference: "KCFM20", quantity: 2},
  {name: "REPARO CENTRAL DA BARRA ANGULAR", reference: "ZL7030", quantity: 1},
  {name: "COXIN SUSPENÇÃO DIANTEIRA ", reference: "77505", quantity: 3},
  {name: "REPARO AMORTECEDOR ", reference: "1050141", quantity: 2},
  {name: "BUCHA DA BARRA ESTABIL DA SUSPENÇÃO", reference: "R-3373", quantity: 1},
  {name: "BUCHA DA BARRA ESTABIL DA SUSPENÇÃO", reference: "R-475", quantity: 1},
  {name: "BUCHA DA BARRA ESTABIL DA SUSPENÇÃO", reference: "R-3372", quantity: 2},
  {name: "ANTICORROSIVO PARA MOTORES", reference: "WURTH", quantity: 4},
  {name: "FLUIDO PARA FREIO", reference: "DOT 4", quantity: 3},
  {name: "FLUIDO PARA FREIO", reference: "DOT3", quantity: 5},
  {name: "ADITIVO PARA RADIADORES", reference: "IPRANGA", quantity: 5},
  {name: "MAX DIESEL ADITIVO PARA DISEL", reference: "PRO MAX", quantity: 8},
  {name: "LIMPA RADIADOR", reference: "WURTH", quantity: 9},
  {name: "LWD POWER DIESEL", reference: "WURTH", quantity: 13},
  {name: "REMOVEDOR DE FERRUGEM", reference: "WURTH", quantity: 3},
  {name: "LIMPA PARA-BRISA", reference: "WURTH", quantity: 1},
  {name: "DESCARBONIZANTE PRO", reference: "WURTH", quantity: 6},
  {name: "HHS 2000 GRAXA LIQUIDA", reference: "WURTH", quantity: 4},
  {name: "REPARADOR PLATICO", reference: "WURTH", quantity: 4},
  {name: "VEDA FLANGE W815", reference: "WURTH", quantity: 3},
  {name: "DESENGRIPANTE", reference: "BRIL LUB", quantity: 4},
  {name: "VEDA CHOQUE", reference: "MAXI RUBBER", quantity: 1},
  {name: "TRAVA ROSCA", reference: "ORBIFIX", quantity: 4},
  {name: "SILICONE PRETO", reference: "SABO", quantity: 3},
  {name: "SILICONE TIPO OXIMIA", reference: "DIRKO HT", quantity: 2},
  {name: "PROTETOR AUDITIVO TIPO CONCHA MOTOQUEIRO", reference: "C.A 18189", quantity: 48},
  {name: "PROTETOR AUDITIVO TIPO CONCHA MAQUINAS", reference: "C.A 19714", quantity: 12},
  {name: "TRENA DE FIBRA DE VIDRO", reference: "30 METROS", quantity: 3},
  {name: "TRENA DE 5M", reference: "5 METROS", quantity: 2},
  {name: "GRANPEADOR", reference: "ROCAMA", quantity: 1},
  {name: "CADEADO 3F", reference: "3F", quantity: 12},
  {name: "PREGOS PARA AJUDANTE", reference: "11X11", quantity: 4},
  {name: "MATELO 18 MM", reference: "18MM", quantity: 14},
  {name: "APRANCHETA", reference: "", quantity: 13},
  {name: "TINTA ALUMINIO PRA MEDIÇAO", reference: "", quantity: 7},
  {name: "GRAMPO ", reference: "80/8 C", quantity: 4},
  {name: "LAPIS DE CERA ESTACA BRANCO", reference: "GIZ", quantity: 10},
  {name: "LAPIS DE CERA ESTACA AZUL", reference: "GIZ", quantity: 90},
  {name: "FILTRO DE COMBUSTÍVEL(CAT)", reference: "3261644", quantity: 9},
  {name: "FILTRO HIDRAULÍCO (CAT)", reference: "152/6902", quantity: 1},
  {name: "FILTRO HIDRAULÍCO (CAT)", reference: "1G8878", quantity: 10},
  {name: "FILTRO HIDRAULÍCO (CAT)", reference: "4331418", quantity: 1},
  {name: "FILTRO DE ÓLEO (CAT)", reference: "1R 1807", quantity: 1},
  {name: "FILTRO DE COMBUSTÍVEL (CAT)", reference: "1R 0749", quantity: 12},
  {name: "TRANSMIÇÃO", reference: "3891079", quantity: 14},
  {name: "FILTRO LUBRIFICANTE", reference: "225 4118", quantity: 1},
  {name: "REFIL", reference: "360 8960", quantity: 1},
  {name: "FILTRO HIDRAULÍCO", reference: "144 0832", quantity: 3},
  {name: "FILTRO LUBRIFICANTE", reference: "1R0739", quantity: 1},
  {name: "FILTRO LUBRIFICANTE", reference: "1R0751", quantity: 8},
  {name: "FILTRO DE ÓLEO", reference: "4T6915", quantity: 1},
  {name: "FILTRO HIDRÁULICO", reference: "132 8876", quantity: 2},
  {name: "FILTRO HIDRÁULICO", reference: "465 6506", quantity: 6},
  {name: "FILTRO HIDRÁULICO", reference: "1R0719", quantity: 1},
  {name: "FILTRO COMBUSTÍVEL", reference: "1R0762", quantity: 7},
  {name: "FILTRO DE ÓLEO", reference: "462 1171", quantity: 7},
  {name: "FILTRO DE ÓLEO", reference: "1R0750", quantity: 1},
  {name: "FILTRO DE ÓLEO", reference: "093-7521", quantity: 1},
  {name: "FILTRO HIDRÁULICO", reference: "341 6643", quantity: 10},
  {name: "FILTRO DE COMBUSTÍVEL", reference: "3375270", quantity: 1},
  {name: "FILTRO HIDRAULICO", reference: "152 6902", quantity: 1},
  {name: "FILTRO COMBUSTIVEL", reference: "439 5037", quantity: 1},
  {name: "FILTRO HIDRÁULICO", reference: "1R 0722", quantity: 7},
  {name: "FILTRO RACOL", reference: "343 5527", quantity: 2},
  {name: "FILTRO DE AR", reference: "245 6375", quantity: 2},
  {name: "FILTRO DE AR", reference: "132 7165", quantity: 1},
  {name: "FILTRO DE AR", reference: "179 9806", quantity: 1},
  {name: "FILTRO DE AR ", reference: "6I2504", quantity: 1},
  {name: "FILTRO DE AR ", reference: "223 3694", quantity: 1},
  {name: "FILTRO DE AR ", reference: "265 6618", quantity: 1},
  {name: "FILTRO DE AR ", reference: "6I 2502", quantity: 2},
  {name: "FILTRO DE AR", reference: "6I 0274", quantity: 1},
  {name: "FILTRO HIDRÁULICO", reference: "422 7912", quantity: 1},
  {name: "FILTRO DE AR ", reference: "545 8339", quantity: 2},
  {name: "FILTRO DE AR ", reference: "121-2761", quantity: 2},
  {name: "FILTRO DE AR", reference: "379-2420", quantity: 1},
  {name: "FILTRO DE COMBUSTÍVEL", reference: "326 1644", quantity: 9},
  {name: "FILTRO HIDRAULÍCO", reference: "152/6902", quantity: 1},
  {name: "FILTRO HIDRAULÍCO", reference: "1G 8878", quantity: 10},
  {name: "FILTRO HIDRAULÍCO", reference: "433 1418", quantity: 1},
  {name: "FILTRO DE ÓLEO", reference: "1R 1807", quantity: 1},
  {name: "FILTRO DE COMBUSTÍVEL", reference: "1R 0749", quantity: 12},
  {name: "FILTRO TRANSMISSÃO", reference: "389 1079", quantity: 14},
  {name: "FILTRO LUBRIFICANTE", reference: "225 4118", quantity: 1},
  {name: "REFIL", reference: "360 8960", quantity: 1},
  {name: "FILTRO HIDRAULÍCO", reference: "144 0832", quantity: 3},
  {name: "FILTRO LUBRIFICANTE", reference: "1R 0739", quantity: 2},
  {name: "FILTRO LUBRIFICANTE", reference: "1R 0751", quantity: 8},
  {name: "FILTRO ÓLEO", reference: "4T 6915", quantity: 1},
  {name: "FILTRO HIDRÁULICO", reference: "132 8876", quantity: 2},
  {name: "FILTRO HIDRÁULICO", reference: "465 6506", quantity: 6},
  {name: "FILTRO HIDRÁULICO", reference: "1R 0719", quantity: 1},
  {name: "FILTRO DE COMBUSTÍVEL", reference: "1R 0762", quantity: 7},
  {name: "FILTRO DE ÓLEO", reference: "462 1171", quantity: 7},
  {name: "FILTRO DE ÓLEO", reference: "1R 0750 ", quantity: 1},
  {name: "FILTRO DE ÓLEO", reference: "093-7521", quantity: 1},
  {name: "FILTRO HIDRÁULICO", reference: "341 6643", quantity: 10},
  {name: "FILTRO DE COMBUSTÍVEL", reference: "337 5270", quantity: 1},
  {name: "FILTRO", reference: "152 6902", quantity: 1},
  {name: "FILTRO DE ÓLEO ( MANN)", reference: "W 962", quantity: 11},
  {name: "FILTRO DE COMBUSTÍVEL ( MANN)", reference: "WK 1040", quantity: 7},
  {name: "FILTRO DE ÓLEO ( MANN)", reference: "W 940/18", quantity: 5},
  {name: "FILTRO DE COMBUSTÍVEL ( MANN)", reference: "W 940/24", quantity: 4},
  {name: "FILTRO DE COMBUSTÍVEL ( MANN)", reference: "WK 1060", quantity: 3},
  {name: "FILTRO DE COMBUSTÍVEL ( MANN)", reference: "WK 1060/4", quantity: 3},
  {name: "FILTRO DE ÓLEO ( MANN)", reference: "WP 12 300", quantity: 3},
  {name: "FILTRO DE ÓLEO ( MANN)", reference: "W 9069", quantity: 2},
  {name: "FILTRO DE COMBUSTÍVEL ( MANN)", reference: "PU 999/1 X", quantity: 1},
  {name: "FILTRO DE COMBUSTÍVEL ( MANN)", reference: "WK10 002/2X", quantity: 1},
  {name: "FILTRO DE COMBUSTÍVEL ( MANN)", reference: "W 718/1", quantity: 7},
  {name: "FILTRO DE COMBUSTÍVEL ( MANN)", reference: "PU 1046 X", quantity: 2},
  {name: "FILTRO DE ÓLEO ( MANN)", reference: "HV 931/5X", quantity: 1},
  {name: "FILTRO DE ÓLEO ( MANN)", reference: "W 712/ 83", quantity: 7},
  {name: "FILTRO HÍDRAULICO ( MANN)", reference: "H 1074", quantity: 2},
  {name: "FILTRO HÍDRAULICO ( MANN)", reference: "WH 980", quantity: 1},
  {name: "FILTRO", reference: "PSH 607", quantity: 13},
  {name: "FILTRO", reference: "PSD 460/ 1", quantity: 9},
  {name: "FILTRO", reference: "PSD 480/1", quantity: 1},
  {name: "FILTRO", reference: "PSD 470/1", quantity: 8},
  {name: "FILTRO", reference: "PSL 962", quantity: 4},
  {name: "FILTRO", reference: "PSD 960/1", quantity: 1},
  {name: "FILTRO", reference: "PSL 280", quantity: 5},
  {name: "FILTRO", reference: "PSD 530/1", quantity: 2},
  {name: "FILTRO", reference: "PSC 410", quantity: 7},
  {name: "FILTRO", reference: "PSC 745", quantity: 11},
  {name: "FILTRO", reference: "PSC 744", quantity: 3},
  {name: "FILTRO", reference: "PSD 420", quantity: 1},
  {name: "FILTRO", reference: "PSH 201", quantity: 4},
  {name: "FILTRO", reference: "PSD 490/1", quantity: 3},
  {name: "FILTRO", reference: "PSH 111", quantity: 3},
  {name: "FILTRO", reference: "PL 447", quantity: 8},
  {name: "FILTRO", reference: "PSL 417", quantity: 6},
  {name: "FILTRO", reference: "PEC 3022", quantity: 2},
  {name: "FILTRO", reference: "PSL 123", quantity: 2},
  {name: "FILTRO", reference: "PSC 880", quantity: 4},
  {name: "FILTRO", reference: "PSC 72/2", quantity: 5},
  {name: "FILTRO", reference: "PSA 331", quantity: 8},
  {name: "FILTRO", reference: "PC 949", quantity: 4},
  {name: "FILTRO", reference: "PL 364", quantity: 1},
  {name: "FILTRO", reference: "PC 2 /155", quantity: 1},
  {name: "FILTRO", reference: "PSH 693", quantity: 1},
  {name: "FILTRO", reference: "PL 366", quantity: 4},
  {name: "FILTRO", reference: "FC 161 ", quantity: 7},
  {name: "FILTRO", reference: "PSH 962", quantity: 1},
  {name: "FILTRO", reference: "PSL 962", quantity: 1},
  {name: "FILTRO", reference: "JCB", quantity: 5},
  {name: "FILTRO", reference: "PSH 025", quantity: 2},
  {name: "FILTRO DE AR", reference: "AS 810", quantity: 1},
  {name: "FILTRO DE AR", reference: "AS 820", quantity: 5},
  {name: "FILTRO DE AR", reference: "AP 2710", quantity: 2},
  {name: "FILTRO DE AR", reference: "ASR 807", quantity: 1},
  {name: "FILTRO DE AR", reference: "ARS 2868", quantity: 2},
  {name: "FILTRO DE AR", reference: "AP 9834", quantity: 3},
  {name: "FILTRO DE AR ", reference: "ARS 8842", quantity: 1},
  {name: "FILTRO DE AR", reference: "ARS 5492", quantity: 1},
  {name: "FILTRO DE AR", reference: "ARS 492", quantity: 1},
  {name: "FILTRO DE AR", reference: "AS 830", quantity: 1},
  {name: "FILTRO DE AR", reference: "AS 571 ", quantity: 3},
  {name: "FILTRO DE AE", reference: "ARS 501", quantity: 4},
  {name: "FILTRO HÍDRAULICO ( TECFIL)", reference: "PH 520", quantity: 1},
  {name: "FILTRO DE AR", reference: "9838", quantity: 1},
  {name: "FILTRO DE AR", reference: "AP 4934", quantity: 1},
  {name: "FILTRO DE AR", reference: "ACP 483", quantity: 3},
  {name: "FILTRO DE AR", reference: "AP 5571", quantity: 2},
  {name: "FILTRO DE ÓLEO ( MAHLE)", reference: "OX69D", quantity: 1},
  {name: "FILTRO DE ÓLEO (MAHLE)", reference: "OC 324", quantity: 1},
  {name: "FILTRO DE COMBUSTÍVEL ( MAHLE)", reference: "KX43", quantity: 1},
  {name: "FILTRO DE ÓLEO (MAHLE)", reference: "OC 275", quantity: 2},
  {name: "FILTRO DE COMBUSTÍVEL (MAHLE)", reference: "KC 24", quantity: 7},
  {name: "FILTRO DE COMBUSTÍVEL (MAHLE)", reference: "KX 24", quantity: 2},
  {name: "FILTRO DE COMBUSTÍVEL (MAHLE)", reference: "KX 23", quantity: 7},
  {name: "FILTRO DE AR (MAHLE)", reference: "LX5 7231", quantity: 1},
  {name: "FILTRO DE AR(MAHLE)", reference: "AP 2710", quantity: 1},
  {name: "FILTRO DE AR (MAHLE)", reference: "LX5 41/1", quantity: 1},
  {name: "FILTRO DE AR (MAHLE)", reference: "LX 1055", quantity: 1},
  {name: "FILTRO DE AR (MAHLE)", reference: "LA 1003", quantity: 1},
  {name: "FILTRO DE AR (MAHLE)", reference: "LX 3713", quantity: 3},
  {name: "FILTRO DE AR (TURBO)", reference: "TR 710", quantity: 1},
  {name: "FILTRO DE AR (TURBO)", reference: "TR 2500", quantity: 1},
  {name: "FILTRO DE AR ( WELA)", reference: "AKX 1955", quantity: 1},
  {name: "FILTRO HÍDRAULICO( DONALDSON)", reference: "P550140", quantity: 5},
  {name: "FILTRO DE COMBUSTÍVEL (DONALDSON)", reference: "P551312", quantity: 1},
  {name: "FILTRO DE AR ( DONALDSON)", reference: "OS32502", quantity: 1},
  {name: "FILTRO DE AR ( DONALDSON)", reference: "P782105", quantity: 2},
  {name: "FILTRO DA  BOMBA( MELOSA )", reference: "39695", quantity: 1},
  {name: "FILTRO HIDRAULÍCO", reference: "H5510", quantity: 2},
  {name: "FILTRO HIDRAULÍCO", reference: "H5506", quantity: 3},
  {name: "FILTRO HIDRAULÍCO", reference: "5512", quantity: 1},
  {name: "FILTRO DE ÓLEO", reference: "C 55221", quantity: 1},
  {name: "FILTRO HIDRAULÍCO", reference: "HC 5504", quantity: 4},
  {name: "FILTRO HIDRAULÍCO", reference: "H 5504", quantity: 2},
  {name: "FILTRO RACOL", reference: "SFC 55170", quantity: 1},
  {name: "FILTRO HIDRAULÍCO", reference: "H 5109", quantity: 1},
  {name: "FILTRO DE AR", reference: "A5550", quantity: 2},
  {name: "FILTRO DE AR", reference: "4 5559", quantity: 3},
  {name: "FILTRO DE AR", reference: "A5510", quantity: 1},
  {name: "FILTRO DE AR", reference: "A 6008", quantity: 1},
  {name: "FILTRO DE AR", reference: "A 5566", quantity: 1},
  {name: "FILTRO DE AR ", reference: "A 5567", quantity: 1},
  {name: "FILTRO DE AR", reference: "A 5549", quantity: 1},
  {name: "TUBO DE PUNHO", reference: "1144-790-1702", quantity: 3},
  {name: "PROTEÇÃO DE MÃO", reference: "1144-790-9100", quantity: 8},
  {name: "PROTEÇÃO DE MÃO", reference: "1122-790-9101", quantity: 1},
  {name: "LIMA CHATA", reference: "1122-790-9101", quantity: 36},
  {name: "LIMA ROLIÇA", reference: "200X5,2 MM", quantity: 54},
  {name: "CORRENTES ", reference: "42", quantity: 26},
  {name: "CORRENTES ", reference: "46", quantity: 3},
  {name: "CAPA DE SABRE", reference: "0000-792-9177", quantity: 3},
  {name: "SABRE (STHIL)", reference: "3003 001 9241 ", quantity: 1},
  {name: "SABRE (STHIL)", reference: "3003 001 56 31", quantity: 2},
  {name: "SABRE (STHIL)", reference: "3005 000 3905", quantity: 1},
  {name: "SABRE (USKARNA)", reference: "501 95 80 92", quantity: 1},
  {name: "SABRE (OREGO)", reference: "248 8 ATMD 009", quantity: 1},
  {name: "PROTEÇÃO ", reference: "1144-656-1500", quantity: 4},
  {name: "CONEXÃO", reference: "1144-141--2205", quantity: 11},
  {name: "EMBREAGEM", reference: "1144-160-2001", quantity: 6},
  {name: "BOMBA DE ÓLEO", reference: "1144-640-3200", quantity: 1},
  {name: "CINTA DO FREIO", reference: "1144-160-5400", quantity: 3},
  {name: "SEM-FIM", reference: "1144-640-7101", quantity: 9},
  {name: "MOLA DE RÉCUO", reference: "1135-190-0600", quantity: 5},
  {name: "LUVA", reference: "1144-123-7500", quantity: 5},
  {name: "JOGO DE PEÇAS DO CARBURADOR", reference: "1144-007-1701", quantity: 8},
  {name: "GAIOLAS DE AGULHAS", reference: "9512-003-3286", quantity: 5},
  {name: "COBERTURA DO PUNHO", reference: "1144-791-0600", quantity: 3},
  {name: "VALVULA DE DESCOMPRESÃO", reference: "1124-020-9401", quantity: 3},
  {name: "EMBREAGEM", reference: "1144-160-2001", quantity: 1},
  {name: "AMORTECEDOR DE EMCOSTO", reference: "1140-791-5901", quantity: 5},
  {name: "TAMPA DO FILTRO", reference: "1144-140-1000", quantity: 2},
  {name: "CARCAÇA DO VIRABREQUIM", reference: "1144-020-2607", quantity: 1},
  {name: "SILENCIADOR", reference: "1144-140-0605", quantity: 3},
  {name: "JOGO DE JUNTA DE VEDAÇÃO", reference: "1144-007-1606", quantity: 11},
  {name: "FILTRO DE AR", reference: "1144-140-4402", quantity: 10},
  {name: "FILTRO DE AR", reference: "1144-140-4400", quantity: 8},
  {name: "CARBURADOR", reference: "1144-120-0625", quantity: 2},
  {name: "CILINDRO COM PISTÃO", reference: "1144-020-1200", quantity: 1},
  {name: "BOMBA DE ÓLEO", reference: "1122-640-3205", quantity: 2},
  {name: "SEM FIM", reference: "1122-640-7105", quantity: 8},
  {name: "MOLA DE RÉCUO", reference: "1122-190-0605", quantity: 9},
  {name: "CONDUTOR DE AR", reference: "1122-141-6300", quantity: 5},
  {name: "CONEXÃO", reference: "1122-141-2201", quantity: 5},
  {name: "PEÇA DE SUJEIÇÃO", reference: "1122-656-1510", quantity: 11},
  {name: "AMORTECEDOR ", reference: "1125-790-9904", quantity: 7},
  {name: "BASE DO FILTRO", reference: "1122-120-3402", quantity: 2},
  {name: "MANGUEIRA DE IMPULSO", reference: "1127-141-8600", quantity: 3},
  {name: "MANGUEIRA ", reference: "1122-647-9400", quantity: 1},
  {name: "EMBREAGEM", reference: "1122-160-2002", quantity: 5},
  {name: "GAIOLAS DE AGULHAS", reference: "9512-933-2382", quantity: 10},
  {name: "ANEL DE VEDAÇÃO", reference: "1122-649-5000", quantity: 1},
  {name: "TERMINAL DE VELA", reference: "1128-405-1000", quantity: 6},
  {name: "AMORTECEDOR", reference: "1122-790-9900", quantity: 5},
  {name: "AMORTECEDOR", reference: "1125-790-9904", quantity: 2},
  {name: "AMORTECEDOR", reference: "1122-790-9905", quantity: 4},
  {name: "FLANGE", reference: "1122-120-2200", quantity: 1},
  {name: "ARUELA", reference: "0000-958-1032", quantity: 10},
  {name: "TIRANTE DO ACELERADOR", reference: "1122-182-1502", quantity: 8},
  {name: "TAMPA", reference: "1122-021-1105", quantity: 7},
  {name: "ARUELA", reference: "1128-121-8600", quantity: 7},
  {name: "MOLA DE TRAÇÃO", reference: "1122-160-5500", quantity: 1},
  {name: "MOLA COM HASTE", reference: "1122-182-4500", quantity: 3},
  {name: "ANEL DE VEDAÇÃO", reference: "9646-945-0490", quantity: 6},
  {name: "ARUELA DE SEGURANÇA", reference: "9460-624-0801", quantity: 10},
  {name: "MOLA", reference: "1122-647-2401", quantity: 5},
  {name: "ANEL DE VEDAÇÃO", reference: "1122-649-5000", quantity: 2},
  {name: "RETENTOR", reference: "9640-003-1560", quantity: 1},
  {name: "TAMPA DO FILTRO", reference: "1122-140-1002", quantity: 6},
  {name: "CARCAÇA DO TANQUE", reference: "1122-350-0826", quantity: 1},
  {name: "SILENCIADOR", reference: "1122-140-0614", quantity: 1},
  {name: "BATENTE DE GARRAS", reference: "1122-664-0501", quantity: 6},
  {name: "BATENTE DE GARRAS", reference: "1122-664-0509", quantity: 2},
  {name: "JUNTA DE VEDAÇÃO", reference: "1122-029-0507", quantity: 1},
  {name: "JUNTA DE VEDAÇÃO", reference: "1122-007-1057", quantity: 12},
  {name: "CINTA DO FREIO", reference: "1122-160-5400", quantity: 10},
  {name: "CARCAÇA DO CARBURADOR", reference: "1122-120-0104", quantity: 3},
  {name: "CILINDRO COM PISTÃO", reference: "1122-020-1209", quantity: 1},
  {name: "COBERTURA", reference: "1122-080-1609", quantity: 2},
  {name: "FILTRO DE AR", reference: "0000-140-4402", quantity: 5},
  {name: "MANÍPULO DE POLIETILENO", reference: "1122-190-3400", quantity: 10},
  {name: "CORDÃO DE ARRANQUE", reference: "1107-195-8200", quantity: 7},
  {name: "TAMPA DO TANQUE", reference: "0000-350-0509", quantity: 15},
  {name: "TAMPA DO TANQUE", reference: "0000-350-0533", quantity: 14},
  {name: "CABEÇOTE DE ASPIRAÇÃO", reference: "0000-350-3518", quantity: 5},
  {name: "CAIXA DE ÓLEO 2 TEMPOS", reference: "MOTOSSERRA", quantity: 2},
  {name: "ÓLEO PRA MOTOSSERA", reference: "MOTOSSERRA", quantity: 28},
  {name: "ÓLEO", reference: "CT50", quantity: 8},
  {name: "ÓLEO MOTOR", reference: "CAT", quantity: 1},
  {name: "ÓLEO TRANSMIÇÃO ", reference: "CAT", quantity: 3},
  {name: "ÓLEO ISOFLUIDO", reference: "433 HD", quantity: 1},
  {name: "ÓLEO ISOFLUIDO", reference: "434TO", quantity: 1},
  {name: "FLUÍDO PARA DIREÇÃO", reference: "-", quantity: 1},
  {name: "ÓLEO MOBIL", reference: "15W40", quantity: 4},
  {name: "ÓLEO IPIRANGA", reference: "15W40", quantity: 7},
  {name: "CAMARA DE AR( CAINHÃO)", reference: "1100-22", quantity: 4},
  {name: "CAMARA DE AR( CAINHÃO)", reference: "1000 R20", quantity: 4},
  {name: "CAMARA DE AR(PATROL)", reference: "1400R24/1300R24", quantity: 3},
  {name: "CAMARA DE AR ( TS 22)", reference: "18.4-34", quantity: 3},
  {name: "CAMARA DE AR ( TS 22)", reference: "17.5R25", quantity: 1},
  {name: "CAMARA DE AR( 938 G)", reference: "20.5R25", quantity: 1},
  {name: "CAMARA DE AR", reference: "295/80R225", quantity: 1},
  {name: "PROTETOR DE CAMERA ( CAMINHÃO)", reference: "22", quantity: 7},
  {name: "PROTETOR DE CAMERA ( CAMINHÃO)", reference: "20", quantity: 3},
  {name: "CHAVE GERAL KHELLER", reference: "884004", quantity: 3},
  {name: "IMPULSOR DE PARTIDA", reference: "105", quantity: 2},
  {name: "BOBINA DE CAMPO, MOTOR DE PARTIDA", reference: "MCK 442.24V", quantity: 1},
  {name: "IMPULSOR DE PARTIDA", reference: "133", quantity: 1},
  {name: "BOBINA JF", reference: "MCM588-12 V", quantity: 1},
  {name: "BOBINA DE CAMPO, MOTOR DE PARTIDA", reference: "NP", quantity: 1},
  {name: "AUTOMÁTICO MOTOR DE PARTIDA(SKID)", reference: "12V-76227", quantity: 2},
  {name: "RELÉ MOTOR DE PARTIDA 24V", reference: "ZM", quantity: 1},
  {name: "IMPULSOR DE PARTIDA", reference: "99009", quantity: 1},
  {name: "INDUZIDO KB 24V ", reference: "123054", quantity: 1},
  {name: "INDUZIDO DE PARTIDA 12 V JF", reference: "20700", quantity: 1},
  {name: "PORTA ESCOVA 12V R", reference: "1121/4", quantity: 1},
  {name: "CHAVE GERAL ", reference: "IM11103", quantity: 1},
  {name: "CHAVE GERAL", reference: "IM13302", quantity: 3},
  {name: "CHAVE GERAL", reference: "IM11108", quantity: 1},
  {name: "PORTA ESCOVA 12V R (SUCARBOM) ", reference: "9001", quantity: 1},
  {name: "RELÉ AUXILIAR ", reference: "DNI-0215", quantity: 2},
  {name: "RELÉ AUXILIAR ", reference: "DNI-0115", quantity: 9},
  {name: "RELE AUXILIAR ", reference: "DNI-0116", quantity: 16},
  {name: "RELE AUXILIAR ", reference: "DNI-0212", quantity: 3},
  {name: "RELE AUXILIAR ", reference: "DNI-0240", quantity: 2},
  {name: "RELE AUXILIAR ", reference: "88RE222", quantity: 3},
  {name: "RELE AUXILIAR ", reference: "DNI-0121", quantity: 2},
  {name: "RELE AUXILIAR ", reference: "DNI-0424", quantity: 2},
  {name: "RELE AUXILIAR ", reference: "DNI-0224S3", quantity: 2},
  {name: "LAMPADA", reference: "H424V75/70W", quantity: 15},
  {name: "LAMPADA", reference: "H724V70W", quantity: 8},
  {name: "LAMPADA", reference: "H324V70W", quantity: 10},
  {name: "LAMPADA", reference: "H1112V", quantity: 2},
  {name: "LAMPADA", reference: "HB312V60W", quantity: 1},
  {name: "LAMPADA", reference: "H412V60", quantity: 8},
  {name: "LAMPADA", reference: "P21/5W24V", quantity: 5},
  {name: "LAMPADA", reference: "H724V70W", quantity: 2},
  {name: "LAMPADA", reference: "T4W12V4W", quantity: 10},
  {name: "LAMPADA", reference: "W5W24V5W", quantity: 19},
  {name: "LAMPADA", reference: "P21W12V21W", quantity: 6},
  {name: "LAMPADA", reference: "P21/5W12V", quantity: 2},
  {name: "LAMPADA", reference: "P21W24V21W", quantity: 9},
  {name: "LAMPADA", reference: "R5W24V5W", quantity: 17},
  {name: "CAPACITOR", reference: "CBB65 380 V", quantity: 2},
  {name: "CAPACITOR", reference: "CBB65 D-30395 380 V", quantity: 1},
  {name: "ROLAMENTO ", reference: "005-74N", quantity: 2},
  {name: "TERMOSTATO", reference: "TE-027000", quantity: 2},
  {name: "PORTA ESCOVA 24V", reference: "1.150/4", quantity: 2},
  {name: "PORTA ESCOVA 12 V", reference: "1.150/4", quantity: 3},
  {name: "RELE DUPLO DE FAROIS", reference: "DNI-8135", quantity: 2},
  {name: "LAMPADA", reference: "R5W12V5W", quantity: 10},
  {name: "RELE AUXILIAR ", reference: "29MT12V 1055812 M", quantity: 2},
  {name: "FITA ISOLANTE AUTA FUSÃO (WURTH)", reference: "-", quantity: 19},
  {name: "FITA ISOLANTE IMPERIAL ", reference: "3M", quantity: 15},
  {name: "CHICOTE BASE PRA RELÉ", reference: "ETE-7595", quantity: 20},
  {name: "CHICOTE BASE REPARO", reference: "ETE-7725", quantity: 4},
  {name: "SIRENE SINALIZADORA", reference: "DNI-4029", quantity: 5},
  {name: "LUMINARIA DE LED", reference: "26032(126W-F)", quantity: 2},
  {name: "FAROL AUXILIAR", reference: "FK-FO126W", quantity: 1},
  {name: "FAROL DE MILHA", reference: "TP-126W", quantity: 2}
]

array.each do |p|
  p[:name] = p[:name].squish!
  p[:filial_id] = filial.id
  
  Product.create(p)
end

# SaleProduct.all.each{|ps| ps.update(prices: Product.find_prices(ps.product_code, ps.quantity))}